# Generated by Django 3.0.5 on 2020-04-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_data',
            new_name='entry_date',
        ),
    ]
